"""add daily_post_comments

Revision ID: 1bc7654ab16e
Revises: c8a4c5424543
Create Date: 2025-08-16 13:11:29.117235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bc7654ab16e'
down_revision: Union[str, Sequence[str], None] = 'c8a4c5424543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_post_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('author_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['daily_post_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['daily_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_post_comments_author_user_id'), 'daily_post_comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_daily_post_comments_parent_id'), 'daily_post_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_daily_post_comments_post_id'), 'daily_post_comments', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_post_comments_post_id'), table_name='daily_post_comments')
    op.drop_index(op.f('ix_daily_post_comments_parent_id'), table_name='daily_post_comments')
    op.drop_index(op.f('ix_daily_post_comments_author_user_id'), table_name='daily_post_comments')
    op.drop_table('daily_post_comments')
    # ### end Alembic commands ###
