"""add creator_id

Revision ID: 7d978ea1b8c0
Revises: e1682e96ec63
Create Date: 2025-09-13 17:29:38.184829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d978ea1b8c0'
down_revision: Union[str, Sequence[str], None] = 'e1682e96ec63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) 先以可空方式添加列
    op.add_column('act_activity', sa.Column('creator_id', sa.Integer(), nullable=True))

    # 2) 用一个安全默认值填充历史数据（例如0，表示未知）
    op.execute('UPDATE act_activity SET creator_id = 0 WHERE creator_id IS NULL')

    # 3) 将列改为非空约束
    op.alter_column('act_activity', 'creator_id', existing_type=sa.Integer(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('act_activity', 'creator_id')
    # ### end Alembic commands ###
