"""add daily_posts and users.member_id

Revision ID: b861d39bb48a
Revises: 50798da5754e
Create Date: 2025-08-12 01:11:01.223479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b861d39bb48a'
down_revision: Union[str, Sequence[str], None] = '50798da5754e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_member_id'), 'users', ['member_id'], unique=True)
    op.create_foreign_key(None, 'users', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_member_id'), table_name='users')
    op.drop_column('users', 'member_id')
    # ### end Alembic commands ###
