"""Add activities table

Revision ID: bed280330e10
Revises: 863c366832cc
Create Date: 2025-07-06 01:09:53.512132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bed280330e10'
down_revision: Union[str, Sequence[str], None] = '863c366832cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.Column('participants_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_title'), 'activities', ['title'], unique=False)
    op.drop_index(op.f('ix_members_avatar_hash'), table_name='members')
    op.drop_column('members', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('avatar_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_members_avatar_hash'), 'members', ['avatar_hash'], unique=False)
    op.drop_index(op.f('ix_activities_title'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
