"""add content_jsonb to daily_posts

Revision ID: c8a4c5424543
Revises: 8bc6b0493d24
Create Date: 2025-08-14 23:53:21.606046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a4c5424543'
down_revision: Union[str, Sequence[str], None] = '8bc6b0493d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_posts', sa.Column('content_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_posts', 'content_jsonb')
    # ### end Alembic commands ###
