"""Update config table with id, type and is_active fields

Revision ID: ff4021c04b72
Revises: 92a5fa66f31c
Create Date: 2025-07-06 21:45:52.806916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff4021c04b72'
down_revision: Union[str, Sequence[str], None] = '92a5fa66f31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('config', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('config', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.drop_column('config', 'is_active')
    op.drop_column('config', 'type')
    op.drop_column('config', 'id')
    # ### end Alembic commands ###
